server:
  port: 8082
spring:
  application:
    name: score-service
  datasource:
    url: jdbc:postgresql://localhost:5432/miniarcade_scores
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  metrics:
    tags:
      application: ${spring.application.name}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
app:
  jwt:
    secret: ${JWT_SECRET}