server:
  port: 8082

spring:
  application:
    name: score-service
  datasource:
    url: jdbc:postgresql://localhost:5432/miniarcade_scores
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true